filebeat_config:
  filebeat:
    prospectors:
      - paths:
          - /var/log/messages
          - /var/log/*.log
        input_type: log
  output:
   logstash:
      # The Logstash hosts
      hosts: ["{{ logstash_host }}:{{ logstash_port }}"]

      # Number of workers per Logstash host.
      #worker: 1
    file:
      path: /tmp/filebeat
      filename: filebeat
  logging:
    to_syslog: true
    level: error