logstash_version: 2.1
logstash_defaults: |
        LS_USER=root
        LS_GROUP=root
        LS_HEAP_SIZE="256m"

logstash_inputs: |
 file {
    path => ["/vagrant/include/example-logs/testlog"]
    start_position => "beginning"
    codec => "json"
    type => "json"
  }
 log4j {
    mode => server
    host => "0.0.0.0"
    port => 9000 
    type => "log4j"
  }

logstash_filters: |

logstash_outputs: |
 file {
    path => "/var/log/logstash/output.log"
    }
 elasticsearch {
    document_type => "example"
    hosts => "127.0.0.1"
  }

